export const API_TAGS = Object.freeze({
  GET_VENDORS: "getVendors",
  GET_MAIN_CATEGORY: "getMainCategory",
  GET_MAIN_CATEGORY_SUB_CATEGORY: "getMainCategorySubCategory",
  GET_SUB_CATEGORY: "getSubCategory",
  GET_SUB_CATEGORY_BY_MAIN_CATEGORY: "getSubCategoryByMainCategory",
  GET_MARKETPLACE_ITEMS: "getMarketplaceItems",
  GET_MARKETPLACE_ITEMS_BY_MAIN_CATEGORY: "getMarketplaceItemsByMainCategory",
  GET_TAXES: "getTaxes",
  GET_DECORATION_PLAN: "getDecorationPlan",
  GET_FOOD_PLAN: "getFoodPlans",
  GET_HALLS: "getHalls",
  // GET_VENDOR_DETAILS: "getVendorDetails",
  // GET_PRICE_LIST: "getPriceList",
  // ADD_PRICE_LIST: "addPriceList",
  // DELETE_PRICE_LIST: "deletePriceList",
  // GET_VENDOR_CATEGORIES: "getVendorCategories",
  // ADD_VENDOR_CATEGORY: "addVendorCategory",
  // DELETE_VENDOR_CATEGORY: "deleteVendorCategory",
  // GET_VENDOR_CATEGORY: "getVendorCategory",
  // GET_VENDOR_ITEMS: "getVendorItems",
  // ADD_VENDOR_ITEMS: "addVendorItems",
  // DELETE_VENDOR_ITEMS: "deleteVendorItems",
  // GET_VENDOR_ITEM_DETAILS: "getVendorItemDetails",
  // GET_VENDOR_ITEM_PRICE_LIST: "getVendorItemPriceList",
  // ADD_VENDOR_ITEM_PRICE_LIST: "addVendorItemPriceList",
  // DELETE_VENDOR_ITEM_PRICE_LIST: "deleteVendorItemPriceList",
  // GET_VENDOR_ITEM_CATEGORIES: "getVendorItemCategories",
  // ADD_VENDOR_ITEM_CATEGORY: "addVendorItemCategory",
  // DELETE_VENDOR_ITEM_CATEGORY: "deleteVendorItemCategory",
  // GET_VENDOR_ITEM_CATEGORY: "getVendorItemCategory",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS: "getVendorItemPriceListDetails",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_ID: "getVendorItemPriceListDetailsById",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_ITEM_ID: "getVendorItemPriceListDetailsByItemId",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_PRICE_LIST_ID: "getVendorItemPriceListDetailsByPriceListId",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_ITEM_ID_AND_PRICE_LIST_ID: "getVendorItemPriceListDetailsByItemIdAndPriceListId",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_ITEM_ID_AND_PRICE_LIST_ID_AND_VENDOR_ID: "getVendorItemPriceListDetailsByItemIdAndPriceListIdAndVendorId",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_ITEM_ID_AND_VENDOR_ID: "getVendorItemPriceListDetailsByItemIdAndVendorId",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_PRICE_LIST_ID_AND_VENDOR_ID: "getVendorItemPriceListDetailsByPriceListIdAndVendorId",
  // GET_VENDOR_ITEM_PRICE_LIST_DETAILS_BY_VENDOR_ID: "getVendorItemPriceListDetailsByVendorId",
});
