export const API_TAGS = Object.freeze({
  GET_VENDORS: "getVendors",
  GET_MAIN_CATEGORY: "getMainCategory",
  GET_MAIN_CATEGORY_SUB_CATEGORY: "getMainCategorySubCategory",
  GET_SUB_CATEGORY: "getSubCategory",
  GET_SUB_CATEGORY_BY_MAIN_CATEGORY: "getSubCategoryByMainCategory",
  GET_MARKETPLACE_ITEMS: "getMarketplaceItems",
  GET_MARKETPLACE_ITEMS_BY_MAIN_CATEGORY: "getMarketplaceItemsByMainCategory",
  GET_TAXES: "getTaxes",
  GET_DECORATION_PLAN: "getDecorationPlan",
  GET_FOOD_PLAN: "getFoodPlans",
  GET_HALLS: "getHalls",
  GET_PURCHASE_ORDERS: "getPurchaseOrders",
  GET_PURCHASE_HISTORY: "getPurchaseHistory",
  GET_IN_HOUSE_INVENTORY: "getInHouseInventory",
  GET_SUITABLE_LIST: "getSuitableList",
  GET_FACILITIES_LIST: "getFacilitiesList",
  GET_BANQUET_TYPE_LIST: "getBanquetTypeList",
  GET_BOOKINGS: "getBookings",
  GET_KITCHEN_LIST: "getKitchenList",
  GET_LAUNDRY_LIST: "getLaundryList",
  GET_HOUSE_KEEPING_LIST: "getHouseKeepingList",
  GET_ELECTRONICS_LIST: "getElectronicsList",
});
